### ISSUE TITLE
Link python files to tutorials

### ISSUE THREAD

**Issue by dgmccart** [acquire-project/acquire-docs#20]
For each tutorial on the website, provide a python file for the user to download. We'd like to automate this process to avoid needing to keep track of updates as content on the website changes. [Mkdocs gallery](https://smarie.github.io/mkdocs-gallery/) may be a suitable solution. @melissawm

**Comment by melissawm** [comment]
This has been partially implemented in #68 , but I can see not all files have been converted. I'll investigate.

**Comment by melissawm** [comment]
It works now 🥳
