### ISSUE TITLE
Copy for the website

### ISSUE THREAD

**Issue by dgmccart** [acquire-project/acquire-docs#21]
# Copy for the Homepage

<img width="651" alt="Screenshot 2023-11-13 at 1 07 21 PM" src="https://github.com/acquire-project/acquire-docs/assets/92180364/a6f996e2-7d27-4ce6-a92d-de01f0804347">

Header tagline: A python package providing a multi-camera video streaming library focused on performant microscopy

# About Acquire
[Acquire](https://github.com/acquire-project/acquire-python) (`acquire-imaging` on [PyPI](https://pypi.org/project/acquire-imaging/)) provides high-speed, multi-camera, video streaming and image acquisition with a programming interface#ADD LINK TO API REFERENCE for streaming video data directly to [napari](https://napari.org/stable/), Python and cloud-friendly file formats.

## Installation

To install Acquire on Windows, macOS, or Ubuntu, simply run the following command:

```
python -m pip install acquire-imaging
```

## Supported Cameras and File Formats
Acquire supports the following cameras (currently only on Windows):

- [Hamamatsu Orca Fusion BT (C15440-20UP)](https://www.hamamatsu.com/eu/en/product/cameras/cmos-cameras/C15440-20UP.html)
- [Vieworks VC-151MX-M6H00](https://www.visionsystech.com/products/cameras/vieworks-vc-151mx-sony-imx411-sensor-ultra-high-resolution-cmos-camera-151-mp)
- [FLIR Blackfly USB3 (BFLY-U3-23S6M-C)](https://www.flir.com/products/blackfly-usb3/?model=BFLY-U3-23S6M-C&vertical=machine+vision&segment=iis)
- [FLIR Oryx 10GigE (ORX-10GS-51S5M-C)](https://www.flir.com/products/oryx-10gige/?model=ORX-10GS-51S5M-C&vertical=machine+vision&segment=iis)

Acquire also supports the following output file formats:

- [Tiff](https://en.wikipedia.org/wiki/TIFF)
- [Zarr](https://zarr.dev/)

For testing and demonstration purposes, Acquire provides a few simulated cameras, as well as raw and trash output devices.

## Citing Acquire
Provide the [CITATION.cff file](https://github.com/acquire-project/acquire-python/blob/main/CITATION.cff)

## Acquire License
`Acquire` is provided under an [Apache 2.0 license](https://github.com/acquire-project/acquire-python/blob/main/LICENSE). You can learn more about the Apache license in the [documentation here](https://www.apache.org/licenses/LICENSE-2.0).

# Copy for Homepage Tiles

Getting Started: Install Acquire and use simulated cameras

API Reference: Information on classes and methods

Tutorials: Guides on using Acquire for specific tasks

For contributors: Learn how to contribute code or documentation to Acquire

# Copy for the Tutorials Homepage
<img width="651" alt="Screenshot 2023-11-13 at 1 07 39 PM" src="https://github.com/acquire-project/acquire-docs/assets/92180364/5081db5a-0e12-4efd-83f6-4335f530cb6e">

Description for the region above the tiles: These tutorials will help you explore the main use cases of Acquire and show examples of using the API. Please [submit an issue on Github](https://github.com/acquire-project/acquire-docs/issues/new) if you'd like to request a tutorial, or if you are also interested in contributing to a tutorial to this documentation please visit our contribution guide#ADD LINK!

Tiles titles (no descriptions provided):
1. Finite Triggered Acquisition
2. Access Data from the Camera
3. Livestream to napari or Matplotlib
4. Select a Streaming or Storage Device
5. Test Camera Drivers
6. Setup Triggers
7. Setup Acquisition Properties
8. Storage Devices In-Detail
9. Save Compressed Data
10. Save Multiscale Data
11. Save Chunked Data

No description below tiles.

**Comment by dgmccart** [comment]
@melissawm

**Comment by melissawm** [comment]
@dgmccart Where should the "Get Started" button point to? The get started page or some other specific content?

**Comment by dgmccart** [comment]
@melissawm Yes, it should point to the get started page.

**Comment by melissawm** [comment]
Hi folks, are there any items left in this issue to follow up on?
