### ISSUE TITLE
Logos in the header are broken

### ISSUE THREAD

**Issue by dgmccart** [acquire-project/acquire-docs#28]
The logos in the header are broken images. 
<img width="491" alt="Screenshot 2023-11-07 at 1 08 46 PM" src="https://github.com/acquire-project/acquire-docs/assets/92180364/7f52eb45-3eed-4420-b292-0309d2c27c40">

@melissawm

**Comment by melissawm** [comment]
Wow, I have never seen this. It looks like the order in which the PRs were merged overwrote some of my changes. Will submit a fix soon. Thanks!

**Comment by dgmccart** [comment]
Sorry about that! I was the one who merged your PRs, and I must have made some mistakes when I resolved conflicts.

**Comment by melissawm** [comment]
No no definitely not you! Maybe some weird bug... Glad it was easy to fix 😄
