### ISSUE TITLE
Drivers.md tutorial is broken

### ISSUE THREAD

**Issue by dgmccart** [acquire-project/acquire-docs#36]
The [drivers.md tutorial](https://github.com/acquire-project/acquire-docs/pull/11) doesn't render properly on the website. The tutorial title shows up as None.
<img width="213" alt="Screenshot 2023-11-15 at 1 54 03 PM" src="https://github.com/acquire-project/acquire-docs/assets/92180364/72dc2faa-48b9-4b8d-acda-137297e8faad">

The tutorial itself doesn't render properly. 
<img width="1512" alt="Screenshot 2023-11-15 at 1 55 39 PM" src="https://github.com/acquire-project/acquire-docs/assets/92180364/514d647a-0935-42c5-96dd-35a92c8c866b">

When the PR was merged, there was a conflict in mkdocs.yaml, so perhaps the conflict wasn't resolved correctly?

**Comment by melissawm** [comment]
As far as I can see this is due to the file not being in the tutorials folder, but in the root of the repo, so mkdocs can't find it. I'll push a fix shortly.

**Comment by dgmccart** [comment]
[PR #37 fixed this](https://github.com/acquire-project/acquire-docs/pull/37)
