### ISSUE TITLE
Reflect changes to chunking API in release 0.2.0

### ISSUE THREAD

**Issue by aliddell** [acquire-project/acquire-docs#42]
The API for configuring chunking has changed in the [latest release](https://pypi.org/project/acquire-imaging/0.2.0/). Now you don't have to specify the chunk size in bytes. Instead, you set all the chunk dimensions.

So for example, where before you had
```
# assuming 1920 x 1080 images with mono8 pixels
config.video[0].storage.settings.chunking.max_bytes_per_chunk = 32 * 2**20 # 32 MB chunks
config.video[0].storage.settings.chunking.tile.width = 1920 // 2
config.video[0].storage.settings.chunking.tile.height = 1080 // 2
```

which would give you 64 frames in a chunk, you can configure it like so:

```
config.video[0].storage.settings.chunk_dims_px.width = 1920 // 2
config.video[0].storage.settings.chunk_dims_px.height = 1080 // 2
config.video[0].storage.settings.chunk_dims_px.planes = 64
```

**Comment by dgmccart** [comment]
Chunking is handled differently in 0.3.0, and PR #86  updates tutorials for 0.3.0.
