### ISSUE TITLE
Homepage cards not rendering properly

### ISSUE THREAD

**Issue by dgmccart** [acquire-project/acquire-docs#55]
The homepage cards should render like this:

<img width="533" alt="Screenshot 2023-11-30 at 11 34 16 AM" src="https://github.com/acquire-project/acquire-docs/assets/92180364/cb71ad5c-1b91-4006-9899-6d39a0ee6ad1">

Instead the cards render like this:

<img width="533" alt="Screenshot 2023-11-30 at 11 35 04 AM" src="https://github.com/acquire-project/acquire-docs/assets/92180364/f5edadec-3026-498b-8e0f-e2081a041045">

**Comment by aliddell** [comment]
They look ok to me [here](https://acquire-project.github.io/acquire-docs/):
<img width="701" alt="image" src="https://github.com/acquire-project/acquire-docs/assets/844464/2498d90b-740e-4880-808e-1a1d3e23d3d9">

**Comment by dgmccart** [comment]
They are loading properly for me now as well.
