### ISSUE TITLE
API reference autogeneration

### ISSUE THREAD

**Issue by dgmccart** [acquire-project/acquire-docs#73]
We'd like to autogenerate our API docs by reading doc strings in the [pyi file](https://github.com/acquire-project/acquire-python/blob/main/python/acquire/acquire.pyi).

**Comment by melissawm** [comment]
I am still trying to figure out the workflow for extracting docstrings from the pyi files. I think that is a possibility, but I am facing this particular issue: https://github.com/mkdocstrings/griffe/issues/81

Will investigate further.

**Comment by melissawm** [comment]
I believe this can be closed - please reopen otherwise!
