### ISSUE TITLE
livestream tutorial download broken. 

### ISSUE THREAD

**Issue by jeskesen** [acquire-project/acquire-docs#76]
The livestream tutorial includes a python script from the examples directory.  It seems that the jupytext script (which loops over all tutorials) does not follow this include directive when generating python.

**Comment by dgmccart** [comment]
Thanks for flagging! Seems like [this PR ](https://github.com/acquire-project/acquire-docs/pull/75)may not have completely fixed the issue. @melissawm

**Comment by melissawm** [comment]
Will look again, thanks for flagging!

**Comment by melissawm** [comment]
Update: after checking, it looks like this will need an extra jinja processing step to get the `include` snippet interpreted before running jupytext.
